#!/usr/bin/env bash
set -euo pipefail

workspace=""
out=""
cargo_lock_backup=""
dpkg_cfg_marker_begin="# BEGIN libjson-safe staged dpkg root"
dpkg_cfg_marker_end="# END libjson-safe staged dpkg root"

cleanup() {
    if [[ -n "${cargo_lock_backup}" && -f "${cargo_lock_backup}" ]]; then
        mv -f "${cargo_lock_backup}" "${workspace}/safe/Cargo.lock"
    fi
}

trap cleanup EXIT

usage() {
    cat <<'EOF'
usage: build-debs.sh --workspace <workspace-copy> --out <artifact-dir>
EOF
}

configure_nonroot_dpkg_install() {
    local dpkg_root dpkg_cfg tmp_cfg

    [[ "$(id -u)" -ne 0 ]] || return 0

    dpkg_root="${HOME}/.local/state/libjson-safe-dpkg-root"
    dpkg_cfg="${HOME}/.dpkg.cfg"

    mkdir -p \
        "${dpkg_root}/var/lib/dpkg" \
        "${dpkg_root}/var/lib/dpkg/info" \
        "${dpkg_root}/var/lib/dpkg/triggers" \
        "${dpkg_root}/var/lib/dpkg/updates" \
        "${dpkg_root}/var/log"
    cp -f /var/lib/dpkg/status "${dpkg_root}/var/lib/dpkg/status"
    if [[ -d /var/lib/dpkg/info ]]; then
        rm -rf "${dpkg_root}/var/lib/dpkg/info"
        mkdir -p "${dpkg_root}/var/lib/dpkg/info"
        cp -a /var/lib/dpkg/info/. "${dpkg_root}/var/lib/dpkg/info/"
    fi

    tmp_cfg="$(mktemp "${HOME}/.dpkg.cfg.libjson-safe.XXXXXX")"
    if [[ -f "${dpkg_cfg}" ]]; then
        awk \
            -v begin="${dpkg_cfg_marker_begin}" \
            -v end="${dpkg_cfg_marker_end}" \
            '
                $0 == begin { skip = 1; next }
                $0 == end { skip = 0; next }
                !skip { print }
            ' \
            "${dpkg_cfg}" >"${tmp_cfg}"
    fi

    cat >>"${tmp_cfg}" <<EOF
${dpkg_cfg_marker_begin}
force-not-root
no-triggers
root=${dpkg_root}
log=${dpkg_root}/var/log/dpkg.log
${dpkg_cfg_marker_end}
EOF
    mv -f "${tmp_cfg}" "${dpkg_cfg}"
}

while (($#)); do
    case "$1" in
        --workspace)
            workspace=${2:?missing value for --workspace}
            shift 2
            ;;
        --out)
            out=${2:?missing value for --out}
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            printf 'unknown option: %s\n' "$1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

[[ -n "${workspace}" ]] || { usage >&2; exit 1; }
[[ -n "${out}" ]] || { usage >&2; exit 1; }
[[ -d "${workspace}" ]] || { printf 'workspace does not exist: %s\n' "${workspace}" >&2; exit 1; }

workspace="$(cd "${workspace}" && pwd)"
mkdir -p "${out}"
out="$(cd "${out}" && pwd)"

[[ -d "${workspace}/safe/debian" ]] || {
    printf 'missing safe/debian under workspace %s\n' "${workspace}" >&2
    exit 1
}

touch "${workspace}/.build-debs-write-test"
rm -f "${workspace}/.build-debs-write-test"

# The safe crate has no external dependencies. A stray ignored Cargo.lock
# generated by a newer host toolchain can still break Ubuntu 24.04's cargo
# during packaging, so build the Debian packages without it.
if [[ -f "${workspace}/safe/Cargo.lock" ]]; then
    cargo_lock_backup="${workspace}/safe/Cargo.lock.build-debs-backup.$$"
    while [[ -e "${cargo_lock_backup}" ]]; do
        cargo_lock_backup="${cargo_lock_backup}x"
    done
    mv "${workspace}/safe/Cargo.lock" "${cargo_lock_backup}"
fi

rm -rf "${workspace}/debian" "${workspace}/build-deb"
mkdir -p "${workspace}/debian"
cp -a "${workspace}/safe/debian/." "${workspace}/debian/"

(
    cd "${workspace}"
    dpkg-buildpackage -rfakeroot -b -us -uc
)

version="$(dpkg-parsechangelog -l"${workspace}/debian/changelog" -SVersion)"
arch="$(dpkg-architecture -qDEB_HOST_ARCH)"
parent_dir="$(dirname "${workspace}")"

artifacts=(
    "${parent_dir}/libjson-c5_${version}_${arch}.deb"
    "${parent_dir}/libjson-c-dev_${version}_${arch}.deb"
    "${parent_dir}/json-c_${version}_${arch}.buildinfo"
    "${parent_dir}/json-c_${version}_${arch}.changes"
)

for artifact in "${artifacts[@]}"; do
    [[ -f "${artifact}" ]] || {
        printf 'missing build artifact: %s\n' "${artifact}" >&2
        exit 1
    }
    cp -f "${artifact}" "${out}/"
done

configure_nonroot_dpkg_install

printf 'wrote Debian artifacts to %s\n' "${out}"
